/*

	PRE-INIT THIS


*/




OL_all_arsenal_items = [
"U_LIB_US_AB_Uniform_M42",
"U_LIB_US_AB_Uniform_M42_506",
"U_LIB_US_AB_Uniform_M42_corporal",
"U_LIB_US_AB_Uniform_M42_FC",
"U_LIB_US_AB_Uniform_M42_Medic",
"U_LIB_US_AB_Uniform_M42_NCO",

"fow_h_us_m2_camo_ace",
"fow_h_us_m2_camo_clover",
"fow_h_us_m2_camo_diamond",
"fow_h_us_m2_camo_heart",
"fow_h_us_m2_camo_open_ace",
"fow_h_us_m2_camo_open_clover",
"fow_h_us_m2_camo_open_diamond",
"fow_h_us_m2_camo_open_heart",
"fow_h_us_m2_camo_open",
"fow_h_us_m2_camo",
"fow_h_us_m2_fak_camo",
"H_LIB_US_AB_Helmet_Clear_1",
"H_LIB_US_AB_Helmet_Clear_2",
"H_LIB_US_AB_Helmet_Clear_3",
"H_LIB_US_AB_Helmet_CO_1",
"H_LIB_US_AB_Helmet_CO_2",
"H_LIB_US_AB_Helmet",
"H_LIB_US_AB_Helmet_2",
"H_LIB_US_AB_Helmet_Jump_1",
"H_LIB_US_AB_Helmet_Jump_2",
"H_LIB_US_AB_Helmet_Medic_1",
"H_LIB_US_AB_Helmet_NCO_1",
"H_LIB_US_AB_Helmet_NCO_2",
"H_LIB_US_AB_Helmet_3",
"H_LIB_US_AB_Helmet_4",
"H_LIB_US_AB_Helmet_5",

"fow_v_us_ab_45",
"fow_v_us_ab_asst_mg",
"fow_v_us_ab_bar",
"fow_v_us_ab_carbine",
"fow_v_us_ab_carbine_eng",
"fow_v_us_ab_carbine_nco",
"fow_v_us_ab_carbine_nco_scr",
"fow_v_us_ab_garand",
"fow_v_us_ab_garand_bandoleer",
"fow_v_us_ab_grenade",
"fow_v_us_ab_thompson",
"fow_v_us_ab_thompson_nco",
"fow_v_us_ab_thompson_nco_scr",
"fow_v_us_45",
"fow_v_us_asst_mg",
"fow_v_us_bar",
"fow_v_us_carbine",
"fow_v_us_carbine_eng",
"fow_v_us_carbine_nco",
"fow_v_us_carbine_nco_scr",
"fow_v_us_garand",
"fow_v_us_garand_bandoleer",
"fow_v_us_grenade",
"fow_v_us_medic",
"fow_v_us_thompson",
"fow_v_us_thompson_nco",
"fow_v_us_thompson_nco_scr",
"V_LIB_US_AB_Vest_Asst_MG",
"V_LIB_US_AB_Vest_Bar",
"V_LIB_US_AB_Vest_Carbine",
"V_LIB_US_AB_Vest_Carbine_nco_Radio",
"V_LIB_US_AB_Vest_Carbine_nco",
"V_LIB_US_AB_Vest_Carbine_eng",
"V_LIB_US_AB_Vest_Garand",
"V_LIB_US_AB_Vest_Grenadier",
"V_LIB_US_AB_Vest_45",
"V_LIB_US_AB_Vest_M1919",
"V_LIB_US_AB_Vest_Padded_Asst_MG",
"V_LIB_US_AB_Vest_Padded_Bar",
"V_LIB_US_AB_Vest_Padded_Carbine",
"V_LIB_US_AB_Vest_Padded_Carbine_nco_Radio",
"V_LIB_US_AB_Vest_Padded_Carbine_nco",
"V_LIB_US_AB_Vest_Padded_Carbine_eng",
"V_LIB_US_AB_Vest_Padded_Garand",
"V_LIB_US_AB_Vest_Padded_Grenadier",
"V_LIB_US_AB_Vest_Padded_45",
"V_LIB_US_AB_Vest_Padded_M1919",
"V_LIB_US_AB_Vest_Padded_Thompson",
"V_LIB_US_AB_Vest_Padded_Thompson_nco_Radio",
"V_LIB_US_AB_Vest_Padded_Thompson_nco",
"V_LIB_US_AB_Vest_Thompson",
"V_LIB_US_AB_Vest_Thompson_nco_Radio",
"V_LIB_US_AB_Vest_Thompson_nco",
"V_LIB_US_Assault_Vest",
"V_LIB_US_Assault_Vest_dday",
"V_LIB_US_Assault_Vest_Light",
"V_LIB_US_Vest_Asst_MG",
"V_LIB_US_Assault_Vest_Thompson",
"V_LIB_US_Vest_Carbine",
"V_LIB_US_Vest_Carbine_eng",
"V_LIB_US_Vest_Garand",
"V_LIB_US_Vest_Grenadier",
"V_LIB_US_Vest_Carbine_nco_Radio",
"V_LIB_US_Vest_Carbine_nco",
"V_LIB_US_Vest_45",
"V_LIB_US_Vest_Bar",
"V_LIB_US_Vest_M1919",
"V_LIB_US_Vest_Thompson_nco",
"V_LIB_US_Vest_Thompson_nco_Radio",
"V_LIB_US_Vest_Thompson",
"V_LIB_US_Vest_Medic",
"V_LIB_US_Vest_Medic2",


"fow_v_us_ab_45",
"fow_v_us_ab_asst_mg",
"fow_v_us_ab_bar",
"fow_v_us_ab_carbine",
"fow_v_us_ab_carbine_eng",
"fow_v_us_ab_carbine_nco",
"fow_v_us_ab_carbine_nco_scr",
"fow_v_us_ab_garand",
"fow_v_us_ab_garand_bandoleer",
"fow_v_us_ab_grenade",
"fow_v_us_ab_thompson",
"fow_v_us_ab_thompson_nco",
"fow_v_us_ab_thompson_nco_scr",
"fow_v_us_45",
"fow_v_us_asst_mg",
"fow_v_us_bar",
"fow_v_us_carbine",
"fow_v_us_carbine_eng",
"fow_v_us_carbine_nco",
"fow_v_us_carbine_nco_scr",
"fow_v_us_garand",
"fow_v_us_garand_bandoleer",
"fow_v_us_grenade",
"fow_v_us_medic",
"fow_v_us_thompson",
"fow_v_us_thompson_nco",
"fow_v_us_thompson_nco_scr",
"V_LIB_US_AB_Vest_Asst_MG",
"V_LIB_US_AB_Vest_Bar",
"V_LIB_US_AB_Vest_Carbine",
"V_LIB_US_AB_Vest_Carbine_nco_Radio",
"V_LIB_US_AB_Vest_Carbine_nco",
"V_LIB_US_AB_Vest_Carbine_eng",
"V_LIB_US_AB_Vest_Garand",
"V_LIB_US_AB_Vest_Grenadier",
"V_LIB_US_AB_Vest_45",
"V_LIB_US_AB_Vest_M1919",
"V_LIB_US_AB_Vest_Padded_Asst_MG",
"V_LIB_US_AB_Vest_Padded_Bar",
"V_LIB_US_AB_Vest_Padded_Carbine",
"V_LIB_US_AB_Vest_Padded_Carbine_nco_Radio",
"V_LIB_US_AB_Vest_Padded_Carbine_nco",
"V_LIB_US_AB_Vest_Padded_Carbine_eng",
"V_LIB_US_AB_Vest_Padded_Garand",
"V_LIB_US_AB_Vest_Padded_Grenadier",
"V_LIB_US_AB_Vest_Padded_45",
"V_LIB_US_AB_Vest_Padded_M1919",
"V_LIB_US_AB_Vest_Padded_Thompson",
"V_LIB_US_AB_Vest_Padded_Thompson_nco_Radio",
"V_LIB_US_AB_Vest_Padded_Thompson_nco",
"V_LIB_US_AB_Vest_Thompson",
"V_LIB_US_AB_Vest_Thompson_nco_Radio",
"V_LIB_US_AB_Vest_Thompson_nco",
"V_LIB_US_Assault_Vest",
"V_LIB_US_Assault_Vest_dday",
"V_LIB_US_Assault_Vest_Light",
"V_LIB_US_Vest_Asst_MG",
"V_LIB_US_Assault_Vest_Thompson",
"V_LIB_US_Vest_Carbine",
"V_LIB_US_Vest_Carbine_eng",
"V_LIB_US_Vest_Garand",
"V_LIB_US_Vest_Grenadier",
"V_LIB_US_Vest_Carbine_nco_Radio",
"V_LIB_US_Vest_Carbine_nco",
"V_LIB_US_Vest_45",
"V_LIB_US_Vest_Bar",
"V_LIB_US_Vest_M1919",
"V_LIB_US_Vest_Thompson_nco",
"V_LIB_US_Vest_Thompson_nco_Radio",
"V_LIB_US_Vest_Thompson",
"V_LIB_US_Vest_Medic",
"V_LIB_US_Vest_Medic2",
"fow_b_us_bandoleer",
"fow_b_us_m2_fueltank",
"fow_b_us_m1928",
"fow_b_usa_m1919_weapon",
"fow_b_usa_m1919_support",
"fow_b_us_m1944",
"fow_b_us_m1944_ropes",
"fow_b_us_m2_mortar_support",
"fow_b_us_m2_mortar_weapon",
"fow_b_us_m2_mortar_adv_weapon",
"fow_b_us_radio",
"fow_b_us_radio_scr",

// UNIFORMS
"U_LIB_US_AB_Uniform_M42",
"U_LIB_US_AB_Uniform_M42_506",
"U_LIB_US_AB_Uniform_M42_corporal",
"U_LIB_US_AB_Uniform_M42_FC",
"U_LIB_US_AB_Uniform_M42_Medic",
"U_LIB_US_AB_Uniform_M42_NCO",



// HELMETS
"fow_h_us_m2_camo_ace",
"fow_h_us_m2_camo_clover",
"fow_h_us_m2_camo_diamond",
"fow_h_us_m2_camo_heart",
"fow_h_us_m2_camo_open_ace",
"fow_h_us_m2_camo_open_clover",
"fow_h_us_m2_camo_open_diamond",
"fow_h_us_m2_camo_open_heart",
"fow_h_us_m2_camo_open",
"fow_h_us_m2_camo",
"fow_h_us_m2_fak_camo",
"H_LIB_US_AB_Helmet_Clear_1",
"H_LIB_US_AB_Helmet_Clear_2",
"H_LIB_US_AB_Helmet_Clear_3",
"H_LIB_US_AB_Helmet_CO_1",
"H_LIB_US_AB_Helmet_CO_2",
"H_LIB_US_AB_Helmet",
"H_LIB_US_AB_Helmet_2",
"H_LIB_US_AB_Helmet_Jump_1",
"H_LIB_US_AB_Helmet_Jump_2",
"H_LIB_US_AB_Helmet_Medic_1",
"H_LIB_US_AB_Helmet_NCO_1",
"H_LIB_US_AB_Helmet_NCO_2",
"H_LIB_US_AB_Helmet_3",
"H_LIB_US_AB_Helmet_4",
"H_LIB_US_AB_Helmet_5",



// VESTS
"fow_v_us_ab_45",
"fow_v_us_ab_asst_mg",
"fow_v_us_ab_bar",
"fow_v_us_ab_carbine",
"fow_v_us_ab_carbine_eng",
"fow_v_us_ab_carbine_nco",
"fow_v_us_ab_carbine_nco_scr",
"fow_v_us_ab_garand",
"fow_v_us_ab_garand_bandoleer",
"fow_v_us_ab_grenade",
"fow_v_us_ab_thompson",
"fow_v_us_ab_thompson_nco",
"fow_v_us_ab_thompson_nco_scr",
"fow_v_us_45",
"fow_v_us_asst_mg",
"fow_v_us_bar",
"fow_v_us_carbine",
"fow_v_us_carbine_eng",
"fow_v_us_carbine_nco",
"fow_v_us_carbine_nco_scr",
"fow_v_us_garand",
"fow_v_us_garand_bandoleer",
"fow_v_us_grenade",
"fow_v_us_medic",
"fow_v_us_thompson",
"fow_v_us_thompson_nco",
"fow_v_us_thompson_nco_scr",
"V_LIB_US_AB_Vest_Asst_MG",
"V_LIB_US_AB_Vest_Bar",
"V_LIB_US_AB_Vest_Carbine",
"V_LIB_US_AB_Vest_Carbine_nco_Radio",
"V_LIB_US_AB_Vest_Carbine_nco",
"V_LIB_US_AB_Vest_Carbine_eng",
"V_LIB_US_AB_Vest_Garand",
"V_LIB_US_AB_Vest_Grenadier",
"V_LIB_US_AB_Vest_45",
"V_LIB_US_AB_Vest_M1919",
"V_LIB_US_AB_Vest_Padded_Asst_MG",
"V_LIB_US_AB_Vest_Padded_Bar",
"V_LIB_US_AB_Vest_Padded_Carbine",
"V_LIB_US_AB_Vest_Padded_Carbine_nco_Radio",
"V_LIB_US_AB_Vest_Padded_Carbine_nco",
"V_LIB_US_AB_Vest_Padded_Carbine_eng",
"V_LIB_US_AB_Vest_Padded_Garand",
"V_LIB_US_AB_Vest_Padded_Grenadier",
"V_LIB_US_AB_Vest_Padded_45",
"V_LIB_US_AB_Vest_Padded_M1919",
"V_LIB_US_AB_Vest_Padded_Thompson",
"V_LIB_US_AB_Vest_Padded_Thompson_nco_Radio",
"V_LIB_US_AB_Vest_Padded_Thompson_nco",
"V_LIB_US_AB_Vest_Thompson",
"V_LIB_US_AB_Vest_Thompson_nco_Radio",
"V_LIB_US_AB_Vest_Thompson_nco",
"V_LIB_US_Assault_Vest",
"V_LIB_US_Assault_Vest_dday",
"V_LIB_US_Assault_Vest_Light",
"V_LIB_US_Vest_Asst_MG",
"V_LIB_US_Assault_Vest_Thompson",
"V_LIB_US_Vest_Carbine",
"V_LIB_US_Vest_Carbine_eng",
"V_LIB_US_Vest_Garand",
"V_LIB_US_Vest_Grenadier",
"V_LIB_US_Vest_Carbine_nco_Radio",
"V_LIB_US_Vest_Carbine_nco",
"V_LIB_US_Vest_45",
"V_LIB_US_Vest_Bar",
"V_LIB_US_Vest_M1919",
"V_LIB_US_Vest_Thompson_nco",
"V_LIB_US_Vest_Thompson_nco_Radio",
"V_LIB_US_Vest_Thompson",
"V_LIB_US_Vest_Medic",
"V_LIB_US_Vest_Medic2",




// BACKPACKS
"fow_v_us_ab_45",
"fow_v_us_ab_asst_mg",
"fow_v_us_ab_bar",
"fow_v_us_ab_carbine",
"fow_v_us_ab_carbine_eng",
"fow_v_us_ab_carbine_nco",
"fow_v_us_ab_carbine_nco_scr",
"fow_v_us_ab_garand",
"fow_v_us_ab_garand_bandoleer",
"fow_v_us_ab_grenade",
"fow_v_us_ab_thompson",
"fow_v_us_ab_thompson_nco",
"fow_v_us_ab_thompson_nco_scr",
"fow_v_us_45",
"fow_v_us_asst_mg",
"fow_v_us_bar",
"fow_v_us_carbine",
"fow_v_us_carbine_eng",
"fow_v_us_carbine_nco",
"fow_v_us_carbine_nco_scr",
"fow_v_us_garand",
"fow_v_us_garand_bandoleer",
"fow_v_us_grenade",
"fow_v_us_medic",
"fow_v_us_thompson",
"fow_v_us_thompson_nco",
"fow_v_us_thompson_nco_scr",
"V_LIB_US_AB_Vest_Asst_MG",
"V_LIB_US_AB_Vest_Bar",
"V_LIB_US_AB_Vest_Carbine",
"V_LIB_US_AB_Vest_Carbine_nco_Radio",
"V_LIB_US_AB_Vest_Carbine_nco",
"V_LIB_US_AB_Vest_Carbine_eng",
"V_LIB_US_AB_Vest_Garand",
"V_LIB_US_AB_Vest_Grenadier",
"V_LIB_US_AB_Vest_45",
"V_LIB_US_AB_Vest_M1919",
"V_LIB_US_AB_Vest_Padded_Asst_MG",
"V_LIB_US_AB_Vest_Padded_Bar",
"V_LIB_US_AB_Vest_Padded_Carbine",
"V_LIB_US_AB_Vest_Padded_Carbine_nco_Radio",
"V_LIB_US_AB_Vest_Padded_Carbine_nco",
"V_LIB_US_AB_Vest_Padded_Carbine_eng",
"V_LIB_US_AB_Vest_Padded_Garand",
"V_LIB_US_AB_Vest_Padded_Grenadier",
"V_LIB_US_AB_Vest_Padded_45",
"V_LIB_US_AB_Vest_Padded_M1919",
"V_LIB_US_AB_Vest_Padded_Thompson",
"V_LIB_US_AB_Vest_Padded_Thompson_nco_Radio",
"V_LIB_US_AB_Vest_Padded_Thompson_nco",
"V_LIB_US_AB_Vest_Thompson",
"V_LIB_US_AB_Vest_Thompson_nco_Radio",
"V_LIB_US_AB_Vest_Thompson_nco",
"V_LIB_US_Assault_Vest",
"V_LIB_US_Assault_Vest_dday",
"V_LIB_US_Assault_Vest_Light",
"V_LIB_US_Vest_Asst_MG",
"V_LIB_US_Assault_Vest_Thompson",
"V_LIB_US_Vest_Carbine",
"V_LIB_US_Vest_Carbine_eng",
"V_LIB_US_Vest_Garand",
"V_LIB_US_Vest_Grenadier",
"V_LIB_US_Vest_Carbine_nco_Radio",
"V_LIB_US_Vest_Carbine_nco",
"V_LIB_US_Vest_45",
"V_LIB_US_Vest_Bar",
"V_LIB_US_Vest_M1919",
"V_LIB_US_Vest_Thompson_nco",
"V_LIB_US_Vest_Thompson_nco_Radio",
"V_LIB_US_Vest_Thompson",
"V_LIB_US_Vest_Medic",
"V_LIB_US_Vest_Medic2",
"fow_b_us_bandoleer",
"fow_b_us_m2_fueltank",
"fow_b_us_m1928",
"fow_b_usa_m1919_weapon",
"fow_b_usa_m1919_support",
"fow_b_us_m1944",
"fow_b_us_m1944_ropes",
"fow_b_us_m2_mortar_support",
"fow_b_us_m2_mortar_weapon",
"fow_b_us_m2_mortar_adv_weapon",
"fow_b_us_radio",
"fow_b_us_radio_scr",
"fow_b_us_rocket_bag",
"B_LIB_US_Bandoleer",
"B_LIB_US_Backpack",
"B_LIB_US_Backpack_Bandoleer",
"B_LIB_US_Backpack_dday",
"B_LIB_US_Backpack_RocketBag_Empty",
"B_LIB_US_Backpack_Mk2",
"B_LIB_US_M2Flamethrower",
"B_LIB_US_M36",
"B_LIB_US_M36_Bandoleer",
"B_LIB_US_M36_Rocketbag_Empty",
"B_LIB_US_M36_Rope",
"B_LIB_US_RocketBag_Empty",
"B_LIB_US_Radio",
"B_LIB_US_Type5",
"B_LIB_US_TypeA3",



// RIFLES
"fow_w_ithaca37",    
"fow_w_m1_carbine",
"fow_w_m1_garand",
"fow_w_m1_garand_2",
"fow_w_m1_garand_l",
"fow_w_m1_thompson",
"fow_w_m1903A1",
"fow_w_m1903A1_sniper",
"fow_w_m1918a2",
"fow_w_m1918a2_bak",
"fow_w_m1919a4",
"fow_w_m1919a6",
"fow_w_m1a1_thompson",
"fow_w_m3",
"fow_w_m55_reising",
"fow_w_M1912",
"LIB_M1A1_Carbine",
"LIB_M1928A1_Thompson",
"LIB_M1928_Thompson",
"LIB_M1919A6",
"LIB_M1919A4",
"LIB_M1918A2_BAR",
"LIB_M1903A4_Springfield",
"LIB_M1903A3_Springfield",
"LIB_M1_Garand",
"LIB_M1_Carbine",
"LIB_M2_Flamethrower",
"LIB_M1A1_Thompson",
"LIB_M3_GreaseGun",

// LAUNCHERS
"fow_w_m1a1_bazooka",
"LIB_M1A1_Bazooka",
"LIB_M2_60_Barrel",
"LIB_M2_60_Tripod",
"LIB_M2_Tripod",

// PISTOLS
"fow_w_m1911",
"LIB_Colt_M1911",
"LIB_Webley_mk6",
"LIB_Webley_Flare",

// ATTACHMENTS
"fow_w_acc_M1897_bayo",
"fow_w_acc_m1_bayo",
"LIB_ACC_M1_Bayo",
"LIB_ACC_M1891_Bayo",
"LIB_ACC_GL_M7",
"fow_w_acc_no4_bayo",
"LIB_ACC_No4_Mk2_Bayo",
"LIB_ACC_P1903_Bayo",
"fow_w_acc_m1918a2_bipod",


// AMMO
"LIB_100Rnd_762x63",
"LIB_100Rnd_762x63_M1",
"LIB_20Rnd_762x63",
"LIB_20Rnd_762x63_M1",
"LIB_50Rnd_762x63",
"LIB_50Rnd_762x63_M1",
"LIB_5Rnd_762x63_t",
"LIB_8Rnd_762x63",
"LIB_8Rnd_762x63_M1",
"LIB_8Rnd_762x63_t",
"LIB_10Rnd_770x56",
"LIB_10Rnd_770x56_MkVIII",
"LIB_30Rnd_M3_GreaseGun_45ACP",
"LIB_30Rnd_45ACP",
"LIB_30Rnd_45ACP_t",
"LIB_50Rnd_45ACP",
"6Rnd_45ACP_Cylinder",
"LIB_7Rnd_45ACP_DeLisle",
"LIB_7Rnd_45ACP",
"9Rnd_45ACP_Mag",
"LIB_6Rnd_455",
"LIB_1Rnd_145x114",
"fow_1Rnd_type10",
"fow_20Rnd_45acp",
"fow_20Rnd_762x63",
"fow_30Rnd_45acp",
"fow_30Rnd_45acp_T",
"fow_50Rnd_45acp",
"fow_50Rnd_45acp_T",
"fow_50Rnd_762x63",
"fow_50Rnd_792x57",
"fow_5Rnd_762x63",
"fow_5Rnd_77x58",
"fow_6Rnd_12G_Pellets",
"fow_6Rnd_12G_Slug",
"fow_6Rnd_455",
"6Rnd_GreenSignal_F",
"6Rnd_RedSignal_F",
"LIB_7Rnd_762x38",
"LIB_100Rnd_792x57",
"LIB_100Rnd_792x57_sS",
"LIB_20Rnd_792x57",
"LIB_10Rnd_792x57_T",
"LIB_10Rnd_792x57_sS",
"LIB_10Rnd_792x57_SMK",
"LIB_10Rnd_792x57_T2",
"LIB_10Rnd_792x57",
"LIB_10Rnd_792x57_clip",
"LIB_50Rnd_792x57",
"LIB_50Rnd_792x57_SMK",
"LIB_50Rnd_792x57_sS",
"LIB_5Rnd_792x57",
"LIB_5Rnd_792x57_t",
"LIB_5Rnd_792x57_SMK",
"LIB_5Rnd_792x57_sS",
"LIB_75Rnd_792x57",
"fow_7Rnd_45acp",
"fow_7Rnd_765x17",
"LIB_1Rnd_RPzB",
"fow_8Rnd_762x63",
"fow_8Rnd_762x63_T",
"fow_8Rnd_765x17",
"fow_13Rnd_9x19",
"fow_8Rnd_8x22",
"fow_8Rnd_9x19",
"LIB_10Rnd_9x19_M1896",
"LIB_32Rnd_9x19",
"LIB_32Rnd_9x19_Sten",
"LIB_32rnd_9x19_t",
"LIB_6Rnd_9x19_Welrod",
"LIB_8Rnd_9x19",
"LIB_8Rnd_9x19_P08",
"LIB_1Rnd_60mm_M6",
"LIB_Bagpipes_Mag",
"LIB_1Rnd_G_DYAKONOV",
"LIB_1Rnd_Faustpatrone",
"fow_flamefuel",
"LIB_1Rnd_flare_green",
"LIB_1Rnd_flare_red",
"LIB_1Rnd_flare_white",
"LIB_1Rnd_flare_yellow",
"LIB_1Rnd_89m_PIAT",
"LIB_1Rnd_89m_G_PIAT",
"fow_1Rnd_60mm_m2_HE",
"fow_1Rnd_60mm_m2_ILL",
"fow_1Rnd_60mm_m2_SMOKE",
"fow_1Rnd_m6a1",
"fow_1Rnd_m9a1",
"LIB_1Rnd_G_M9A1",
"LIB_1Rnd_G_Mk2",
"fow_e_m24K_at",
"LIB_1Rnd_G_MillsBomb",
"LIB_1Rnd_G_SPRGR_30",
"fow_1Rnd_type2_40",
"fow_1Rnd_81mm_type97_HE",
"fow_1Rnd_81mm_type97_ILL",
"fow_1Rnd_81mm_type97_SMOKE",



// EXPLOSIVES
"LIB_F1",
"fow_e_mk2",
"LIB_US_Mk_2",
"LIB_US_TNT_4pound_mag",
"LIB_Ladung_Big_MINE_mag",
"LIB_Ladung_Small_MINE_mag",
"LIB_US_M1A1_ATMINE_mag",
"LIB_M3_MINE_mag",
"LIB_US_M3_MINE_mag",
"APERSTripMine_Wire_Mag",
"LIB_PMD6_MINE_mag",
"LIB_SMI_35_MINE_mag",
"LIB_SMI_35_1_MINE_mag",
"LIB_TM44_MINE_mag",
"LIB_TMI_42_MINE_mag",
"fow_e_tnt_onepound_mag",
"fow_e_tnt_twohalfpound_mag",
"fow_e_tnt_twopound_mag",
"SmokeShell",
"LIB_No77",
"fow_e_no77",
"fow_e_no79",
"LIB_US_M18",
"LIB_US_M18_Green",
"LIB_US_M18_Red",
"LIB_US_M18_Yellow",
"fow_e_tnt_halfpound",


// ITEMS
"LIB_US_TNT_4pound_mag",
"LIB_Ladung_Big_MINE_mag",
"LIB_Ladung_Small_MINE_mag",
"LIB_US_M1A1_ATMINE_mag",
"LIB_M3_MINE_mag",
"LIB_US_M3_MINE_mag",
"APERSTripMine_Wire_Mag",
"LIB_PMD6_MINE_mag",
"LIB_SMI_35_MINE_mag",
"LIB_SMI_35_1_MINE_mag",
"LIB_TM44_MINE_mag",
"LIB_TMI_42_MINE_mag",
"fow_e_tnt_onepound_mag",
"fow_e_tnt_twohalfpound_mag",
"fow_e_tnt_twopound_mag",
"fow_i_fak_us_red",
"fow_i_fak_us",
"fow_i_rangeTables_type97",
"fow_g_gloves4",
"fow_g_gloves5",
"fow_g_gloves6",
"fow_g_gloves2",
"fow_g_gloves1",
"fow_g_gloves3",
"fow_g_watch2",
"fow_g_watch1",
"fow_g_glasses4",
"G_LIB_Dust_Goggles",
"G_LIB_GER_Gloves4",
"G_LIB_GER_Gloves5",
"G_LIB_GER_Gloves2",
"G_LIB_GER_Gloves1",
"G_LIB_GER_Gloves3",
"G_LIB_Watch2",
"G_LIB_Watch1",
"fow_i_nvg_US_A4Wool_Beige",
"fow_i_nvg_US_A4Wool_Blue",
"fow_i_nvg_US_A4Wool_Green",
"fow_i_nvg_US_scr",
"LIB_GER_Gloves4",
"LIB_GER_Gloves5",
"LIB_GER_Gloves2",
"LIB_GER_Gloves1",
"LIB_GER_Gloves3",
"Binocular",
"FirstAidKit",
"ItemRadio"

];











//****************************************
//         ACE CHECK
//****************************************
if ( (isClass(configFile >> "CfgPatches" >> "ace_main")) ) then {



	private _aceItems = [

	"ACE_RangeTable_82mm",
	"ACE_adenosine",
	"ACE_artilleryTable",
	"ACE_ATragMX",
	"ACE_Banana",
	"ACE_fieldDressing",
	"ACE_elasticBandage",
	"ACE_packingBandage",
	"ACE_quikclot",
	"ACE_bloodIV",
	"ACE_bloodIV_250",
	"ACE_bloodIV_500",
	"ACE_bodyBag",
	"ACE_CableTie",
	"ACE_Can_Franta",
	"ACE_Can_RedGull",
	"ACE_Can_Spirit",
	"ACE_Canteen",
	"ACE_Canteen_Empty",
	"ACE_Canteen_Half",
	"ACE_Cellphone",
	"ACE_Chemlight_Shield",
	"ACE_DAGR",
	"ACE_DeadManSwitch",
	"ACE_DefusalKit",
	"ACE_EarPlugs",
	"ACE_EntrenchingTool",
	"ACE_epinephrine",
	"ACE_Fortify",
	"ACE_Flashlight_MX991",
	"ACE_Humanitarian_Ration",
	"ACE_HuntIR_monitor",
	"ACE_Kestrel4500",
	"ACE_IR_Strobe_Item",
	"ACE_Flashlight_KSF1",
	"ACE_M26_Clacker",
	"fow_i_rangeTables_m2",
	"ACE_Clacker",
	"ACE_Flashlight_XL50",
	"ACE_MapTools",
	"Medikit",
	"ACE_microDAGR",
	"MineDetector",
	"ACE_morphine",
	"ACE_MRE_BeefStew",
	"ACE_MRE_ChickenHerbDumplings",
	"ACE_MRE_ChickenTikkaMasala",
	"ACE_MRE_CreamChickenSoup",
	"ACE_MRE_CreamTomatoSoup",
	"ACE_MRE_LambCurry",
	"ACE_MRE_MeatballsPasta",
	"ACE_MRE_SteakVegetables",
	"ACE_personalAidKit",
	"ACE_plasmaIV_250",
	"ACE_plasmaIV_500",
	"ACE_RangeCard",
	"ACE_rope12",
	"ACE_rope15",
	"ACE_rope18",
	"ACE_rope27",
	"ACE_rope3",
	"ACE_rope36",
	"ACE_rope6",
	"ACE_salineIV",
	"ACE_salineIV_250",
	"ACE_salineIV_500",
	"ACE_Sandbag_empty",
	"LIB_ToolKit",
	"fow_i_whistle",
	"ACE_SpareBarrel_Item",
	"ACE_splint",
	"ACE_SpottingScope",
	"ACE_SpraypaintBlack",
	"ACE_SpraypaintBlue",
	"ACE_SpraypaintGreen",
	"ACE_SpraypaintRed",
	"ACE_surgicalKit",
	"ToolKit",
	"ACE_Tripod",
	"ACE_tourniquet",
	"ACE_UAVBattery",
	"ACE_WaterBottle",
	"ACE_WaterBottle_Empty",
	"ACE_WaterBottle_Half",
	"ACE_wirecutter"

	];
	
	
	{

		OL_all_arsenal_items pushBackUnique _x;
		
	} forEach _aceItems;
	 
};






//****************************************
//         TFAR CHECK
//****************************************
if ( (isClass(configFile >> "CfgPatches" >> "tfar_handhelds")) ) then {

	private _tfar = [
	"TFAR_anprc148jem",
	"TFAR_anprc152",
	"TFAR_anprc154",
	"TFAR_fadak",
	"TFAR_pnr1000a",
	"TFAR_rf7800str"
	];

	{

		OL_all_arsenal_items pushBackUnique _x;
		
	} forEach _tfar;
		
	
};	
	
	
	
	
	
	
//****************************************
//         SET ARSENAL
//****************************************	
publicVariable "OL_all_arsenal_items";

[missionNameSpace, OL_all_arsenal_items, true] call BIS_fnc_addVirtualBackpackCargo;
[missionNameSpace, OL_all_arsenal_items, true] call BIS_fnc_addVirtualItemCargo;
[missionNameSpace, OL_all_arsenal_items, true] call BIS_fnc_addVirtualMagazineCargo;
[missionNameSpace, OL_all_arsenal_items, true] call BIS_fnc_addVirtualWeaponCargo;	
	
	
	
	
	
	
	
	
	
	
	
	



